### ISSUE TITLE
codeblock under osx 10.10.3 using the gnu gcc compiler

### ISSUE THREAD

**Issue by yanko** [TomCrypto/Lambda#1]
when I try to compile the project i get this error:
g++ -std=c++0x -Wall -fexceptions -fopenmp -march=core2 -g -I./include/ -c /Users/me/Downloads/Lambda-master/src/renderer/renderer.cpp -o obj/debug/src/renderer/renderer.o
clang: warning: argument unused during compilation: '-fopenmp'
/Users/me/Downloads/Lambda-master/src/renderer/renderer.cpp:7:10: fatal error: 'omp.h' file not found
# include <omp.h>

where can I get the omp lib?

tx.

**Comment by TomCrypto** [comment]
Trying using `clang++` instead (see http://stackoverflow.com/questions/20807024/trying-to-install-openmp-clang-on-mac)

I have never tested the code on OS X however. It may not work.

**Comment by yanko** [comment]
tried...getting the below... how hard is it to get the openmp installed?

-------------- Build: Debug in Lambda (compiler: LLVM Clang Compiler)---------------

clang++ -std=c++0x -Wall -fexceptions -fopenmp  -g -march=core2    -I./include/ -c /Users/me/Downloads/Lambda-master/src/renderer/renderer.cpp -o obj/debug/src/renderer/renderer.o
clang: warning: argument unused during compilation: '-fopenmp'
/Users/me/Downloads/Lambda-master/src/renderer/renderer.cpp:7:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^
1 error generated.

**Comment by TomCrypto** [comment]
I honestly don't know, I have near zero experience with OS X and much less adding openmp support to clang (all the clang distributions I worked with had openmp preinstalled). You may have to ask around the apple clang support forum for that. Sorry that I can't be of more help...

**Comment by yanko** [comment]
I ll install ubuntu in a vm and try it. tx tho.

**Comment by yanko** [comment]
question, does clang come with openmp? do you know a site where it shows how to run it on ubuntu 14.10? tx a bunch.

**Comment by TomCrypto** [comment]
Well since you're going to install ubuntu you may as well use g++ in that case I think (which certainly comes with openmp).

**Comment by yanko** [comment]
I got llvm to run and compiled the project with codeblock...
I am running it now see below.... waiting for it to finish processing..
the spheres file is in the same folder as Lambda.

[+] Scene file to render: spheres
[+] Output file: spheres.ppm
[+] Thread count: 8

[+] Opening <spheres>...

[+] Scene file header:
    | 1829240864×1818322031.
    | 7561577 spp.

[+] Parsing scene entities...

**Comment by yanko** [comment]
been running for 14h now... nothing...
must be doing something wrong...

**Comment by TomCrypto** [comment]
Yes, it looks like it was not loaded properly. I might look into it if I have time - I haven't touched this codebase in over two years. Not sure why there would be issues though.
